language: php
sudo: false

php:
  - 7.4

cache:
  directories:
    - "$HOME/.composer/cache"

matrix:
  fast_finish: true

install:
  - composer install

script:
  - cat composer.json
  - ls -al vendor/
  - ls -al vendor/bin
  - vendor/bin/pretty
  - vendor/bin/phpunit
  - vendor/bin/deptrack